defmodule Fleetms.Repo.TenantMigrations.AddVehicleResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:vehicles, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :category, :text
      add :type, :text
      add :body_style, :text
      add :license_plate, :text
      add :vin, :text
      add :year, :bigint
      add :purchase_date, :date
      add :purchase_price, :decimal
      add :color, :text
      add :photo, :text
      add :mileage_in_distance, :decimal, default: "0"
      add :status, :text, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :vehicle_model_id,
          references(:vehicle_models,
            column: :id,
            name: "vehicles_vehicle_model_id_fkey",
            type: :uuid,
            prefix: prefix(),
            on_delete: :delete_all
          )
    end

    create unique_index(:vehicles, [:name], name: "vehicles_unique_name_index")
  end

  def down do
    drop_if_exists unique_index(:vehicles, [:name], name: "vehicles_unique_name_index")

    drop constraint(:vehicles, "vehicles_vehicle_model_id_fkey")

    drop table(:vehicles, prefix: prefix())
  end
end
