defmodule Fleetms.Repo.TenantMigrations.AddIdentities do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:vehicle_models, [:name], name: "vehicle_models_unique_name_index")

    create unique_index(:vehicle_makes, [:name], name: "vehicle_makes_unique_name_index")
  end

  def down do
    drop_if_exists unique_index(:vehicle_makes, [:name], name: "vehicle_makes_unique_name_index")

    drop_if_exists unique_index(:vehicle_models, [:name],
                     name: "vehicle_models_unique_name_index"
                   )
  end
end
