defmodule :"Elixir.Fleetms.Repo.TenantMigrations.Make fields null" do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:vehicles, prefix: prefix()) do
      modify :status, :text, null: true
      modify :year, :bigint, null: true
    end
  end

  def down do
    alter table(:vehicles, prefix: prefix()) do
      modify :year, :bigint, null: false
      modify :status, :text, null: false
    end
  end
end
