defmodule Fleetms.Repo.TenantMigrations.VehicleMakeAndModelResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:vehicle_models, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :details, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :vehicle_make_id, :uuid, null: false
    end

    create table(:vehicle_makes, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:vehicle_models, prefix: prefix()) do
      modify :vehicle_make_id,
             references(:vehicle_makes,
               column: :id,
               name: "vehicle_models_vehicle_make_id_fkey",
               type: :uuid,
               prefix: prefix(),
               on_delete: :delete_all
             )
    end

    alter table(:vehicle_makes, prefix: prefix()) do
      add :name, :text, null: false
      add :details, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:vehicle_makes, prefix: prefix()) do
      remove :updated_at
      remove :created_at
      remove :details
      remove :name
    end

    drop constraint(:vehicle_models, "vehicle_models_vehicle_make_id_fkey")

    alter table(:vehicle_models, prefix: prefix()) do
      modify :vehicle_make_id, :uuid
    end

    drop table(:vehicle_makes, prefix: prefix())

    drop table(:vehicle_models, prefix: prefix())
  end
end
