image:
  file: .gitpod.Dockerfile

tasks:
  - name: "Phoenix Dev Server"
    init: |
      mix setup
      mix compile
    command: iex -S mix phx.server

ports:
  - port: 4000
    onOpen: open-preview

vscode:
  extensions:
    # - vscodevim.vim
    - asvetliakov.vscode-neovim
    - elixir-lsp.elixir-ls
    - elixir-tools.elixir-tools
    - pantajoe.vscode-elixir-credo
    - bradlc.vscode-tailwindcss
    - benvp.vscode-hex-pm-intellisense
    - victorbjorklund.phoenix
    - PKief.material-icon-theme
