services:
  app:
    build: .
    container_name: fleetms 
    env_file:
      - prod.env
    volumes:
      - fleetms_data:/app
    networks:
      - app-network
    depends_on:
      - db
    ports:
      - "4000:4000"
    restart: always

  db:
    image: postgres:15
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - prod.env
    networks:
      - app-network
    ports:
      - "5432:5432"
    restart: always

volumes:
  pgdata:
  fleetms_data:

networks:
  app-network:
    driver: bridge
