defmodule Fleetms.Repo.Migrations.AddIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:organizations, [:name], name: "organizations_unique_name_index")
  end

  def down do
    drop_if_exists unique_index(:organizations, [:name], name: "organizations_unique_name_index")
  end
end
