defmodule Fleetms.Repo.Migrations.AddAttributesToUserProfile do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_profiles) do
      add :phone_number, :text
      add :secondary_phone_number, :text
      add :date_of_birth, :date
      add :profile_photo, :text
    end
  end

  def down do
    alter table(:user_profiles) do
      remove :profile_photo
      remove :date_of_birth
      remove :secondary_phone_number
      remove :phone_number
    end
  end
end
